# Generated by Django 4.0.4 on 2022-05-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
